config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users

  root :to =>"homes#top"
  get 'home/about'=>'homes#about', as:'about'
  
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search",to: "users#search"
  end  

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true,length: { maximum: 200 } 
    

    def favorited_by?(user,book)
     favorites.where(user_id: user.id,book_id: book.id).exists?
    end    

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true


end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :chats
    has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  validates :name, presence: true,length: { in: 2..20 },uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   has_many :followings, through: :relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower
   has_many :user_rooms,dependent: :destroy
   has_many :chats,dependent: :destroy
   
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end
# フォローを外すときの処理
  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end
# フォローしているか判定
  def following?(user)
   followings.include?(user)
  end
  
  
  

   
 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
 end
 
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:top, :about]

    
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all
    
  end

  def show
    @book_new=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
    @book_comment = BookComment.new
  end
  
  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user=current_user
      @books=Book.all
      render :index
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book) 
    else
      render :edit
    end 
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def edit
    @book=Book.find(params[:id])
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id,room_id: rooms)
    
    if user_room.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_room.room
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
    
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to chat_path(@chat.room.id)
  end
  
  private
  
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 
 def create
  @book = Book.find(params[:book_id])
  favorite = current_user.favorites.new(book_id: @book.id)
  favorite.save

 end
 
 def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  
 end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  

  def index
    @book=Book.new
    @user=current_user
    @users=User.all
  end

  def show
    @book=Book.new
    @user=User.find(params[:id])
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully." 
      redirect_to user_path(@user)
    else
      render :edit
    end  
    
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    @book = @user.books
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_form.html.erb
<div>
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
    <div class="form-group">
      <lable for="book_title">Title</lable>
      <%= f.text_field :title,class:"form-control book_title" %>
    </div>  
    <div class="form-group">
      <lable for="book_opinion">Opinion</h5>
      <%= f.text_area :body,class:"form-control book_body" %>
    </div>  
    <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
    </div>
    <% end %>
    
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>      

<%= form_with model: @book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"form-control book_body" %>
  </div> 
  <div class="form-group">
    <%= f.submit 'Update Book',class:"btn btn-success" %>
  </div> 

  <%=link_to "Show", book_path(@book) %> |
  <%= link_to "Back", books_path %>
<% end %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>  
    

<div class="container px-5 px-sm-0">
  <div class= "row">
      <div class="col-md-3">
        <%= render 'users/user_info',user:@user %>
        <%= render 'book_form',book:@book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>

        <table class="table">
         <thead>
            <tr>
             <th>&nbsp;</th>
             <th>Title</th>
             <th>Opinion</th>
            </tr>
         </thead>
         <tbody>
        <% @books.each do |book| %>
           <tr>
             <td>
                <%= link_to user_path(book.user.id) do %>
                 <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
             </td>
             <td>
                 <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                 <% end %>
             </td>
             <td>
                 <%= book.body %>
             </td>
             <td class=<%="favorites-btn-" + book.id.to_s %>><%= render "favorites/favorites", book: book %></td>
                 
                 
         <% end %>
           </tr>
         </tbody>
        </table>
    
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-3">
<%= render 'users/user_info',user:@user %>
<%= render 'book_form',book:@book_new %>
</div>

<div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>


 <table class="table">
 <tbody>

    <tr>
     <td><%= link_to user_path(@user.id) do %>
         <%= image_tag @user.get_profile_image(100,100) %>
         <% end %>
         </br>
         <%= link_to @user.name, user_path(@user.id) %>
     </td>
     <td><%= link_to @book.title, book_path(@book.id) %></td>
     <td><%= @book.body %></td>
     <td class=<%="favorites-btn-" + @book.id.to_s %>><%= render "favorites/favorites", book: @book %></td>
     <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
     <% if @user == current_user %>
     <td><%=link_to "Edit",edit_book_path(@book.id),class:"btn btn-sm btn-success edit_book_15730" %></td>
     <td><%= link_to "Destroy", book_path(@book.id), method: :delete,"data-confirm" => "Are you sure？",class:"btn btn-sm btn-danger destroy_book_15730" %></td>
      <% end %>
    
    </tr>
</tbody>
</table>
 <table class="book_comments">
  <%= render "book_comments/index",book: @book %>
 </table>
 <%= form_with model:[@book,@book_comment],local: false do |f| %>
  <%= f.text_area :comment, size:"90*5" %>
  <%= f.submit "送信" %>
 <% end %> 
</div>
</div>

app/views/chats/create.js.erb
<!--/*.messageを部分更新。appendメソッドで要素を追加 */-->
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");

<!--/*チャット投稿後、フォームの値に前回の投稿内容が残らないようにする */-->
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
        <h2><%= @user.name %>さんとのチャット</h2>
        <div>
          <% if @chats.present? %>
            <% @chats.each do |c| %>
            <strong><%= c.message %></strong>
        </div>
        <div class="chat-hukidashi"><br>
            <% end %>
          <% end %>
        </div>
         <div class="posts">
          <%= form_with model: @chat, data: {remote: true} do |f| %>
           <%= f.text_field :message, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
           <%= f.hidden_field :room_id %>
           <%= f.submit "投稿",class: 'form-submit'%>
          <% end %>
         </div>
        </div>
    </div>
</div>            

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user,book) %>
    <!--# 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ-->
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        <span style="color:red;">♥<%= book.favorites.count %></span>
        
    <% end %>
<% else %>
    <!--# 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ-->
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        <span>♡<%= book.favorites.count %>︎</span>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorites-btn-<%= @book.id %>').html("<%= j(render "favorites/favorites",book: @book) %>");

app/views/favorites/destroy.js.erb
$('.favorites-btn-<%= @book.id %>').html("<%= j(render "favorites/favorites",book: @book) %>");

app/views/users/_user_info.html.erb
<div>
    <h2>User info</h2>
    <p><%= image_tag user.get_profile_image(100,100) %></p>
    <table class="table">
     <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%=user.introduction %></th>
        </tr>
        <tr>
          <th>follows: 
           <%= link_to user.followings.count,user_followings_path(user)  %>
          </th>
          
        </tr>
        <tr>
          <th>followers:
           <%= link_to user.followers.count,user_followers_path(user)  %>
          </th>
        </tr>
     </tbody>
    </table>
  <div class="row"> 
  
    <% if user.id==current_user.id && %> 
     <%= link_to edit_user_path(user),class:"btn btn-outline-secondary btn-block edit_user_20596" do%>
     <i class="fas fa-user-cog"></i>
     <% end %>
    <% else %>
     <%= link_to edit_user_path(user),class:"btn btn-outline-secondary btn-block edit_user_20596" do%>
     <i class="fas fa-user-cog"></i>
     <% end %>
     <% end %>
     
  </div>    
</div>  
    
  

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
        <h2>User info</h2>
          <% if @user.errors.any? %>
            <%= @user.errors.count %>error prohibited this obj from being saved:
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
    
    
         <%= form_with model: @user do |f| %>
          <div class="form-group">
           <label for="inputName">Name</label>
           <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前",class:"form-control name"%>
          </div>
          
          <div class="form-group">
           <label for="inputImage">Image</label>
           <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" ,class:"form-control-file user_image" %>
          </div>
          <div class="form-group">
           <label for="inputIntroduction">Introduction</label>
           <%= f.text_area :introduction,class:"form-control introduction" %>
          </div>
          <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-secondary" %>
          </div>
         <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <%= render 'users/user_info',user:@user %>
   <%= render 'books/book_form',book:@book %>
   
　</div>
   <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   
    <table class="table">
    <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th>&nbsp;</th>
       </tr>
    </thead>
    <tbody>
   <% @users.each do |user| %>
       <tr>
        <td><%= image_tag user.get_profile_image(100,100) %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to "Show",user_path(user.id) %></td>
       </tr>
    <% end %>
    </tbody>
   </table>
   </div>
  </div>    
</div>
    

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">

     <%= render 'users/user_info',user:@user %>
     <% if current_user.following?(@user) %>
      <%= link_to "フォロー外す", user_relationships_path(@user), method: :delete, class:"btn btn-primary" %>
     <% else %>
      <%= link_to "フォローする", user_relationships_path(@user), method: :post, class:"btn btn-success" %>
     <% end %>
     
  <% if current_user != @user %>
   <%= link_to 'chatを始める', chat_path(@user.id) %>
  <% end %> 
        
     <%= render 'books/book_form',book:@book %>
  </div>   
     
     <div class="col-md-8 offset-md-1">
         <h2>Books</h2>
     
      <table class="table">
      <thead>
         <tr>
          <th>&nbsp;</th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
      </thead>
      <tbody>
     <% @books.each do |book| %>
         <tr>
          <td>
             <%=link_to (book.user) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
             <% end %>
          </td>
          <td>
              <%= link_to book_path(book.id) do %>
               <%= book.title %>
              <% end %>
          </td>
          <td><%= book.body %></td>
         </tr>
      <% end %>
      </tbody>
     </table>
         
     </div>
 </div>    
</div>