config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users

  root :to =>"homes#top"
  get 'home/about'=>'homes#about', as:'about'
  
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search",to: "users#search"
  end  

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true,length: { maximum: 200 } 
    

    def favorited_by?(user,book)
     favorites.where(user_id: user.id,book_id: book.id).exists?
    end    

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true


end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :chats
    has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  validates :name, presence: true,length: { in: 2..20 },uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   has_many :followings, through: :relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower
   has_many :user_rooms,dependent: :destroy
   has_many :chats,dependent: :destroy
   
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end
# フォローを外すときの処理
  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end
# フォローしているか判定
  def following?(user)
   followings.include?(user)
  end
  
  
  

   
 def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
 end
 
  
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all
    
  end

  def show
    @book_new=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
    @book_comment = BookComment.new
  end
  
  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user=current_user
      @books=Book.all
      render :index
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book) 
    else
      render :edit
    end 
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def edit
    @book=Book.find(params[:id])
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id,room_id: rooms)
    
    if user_room.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_room.room
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
    
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to chat_path(@chat.room.id)
  end
  
  private
  
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  

  def index
    @book=Book.new
    @user=current_user
    @users=User.all
  end

  def show
    @book=Book.new
    @user=User.find(params[:id])
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully." 
      redirect_to user_path(@user)
    else
      render :edit
    end  
    
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    @book = @user.books
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">  
      <a class="navbar-brand" href="/">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
    
        <% if user_signed_in? %>
        <li>
            <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
             <i class="fas fa-home"></i>Home
            <% end %>
        </li>
        
        <li>
          <%= link_to users_path,class: "nav-link text-light" do  %>
            <i class="fas fa-users"></i>Users
          <% end %>
        </li>
        
        <li>
          <%= link_to books_path,class: "nav-link text-light" do %>
            <i class="fas fa-book-open"></i>Books
          <% end %>
        </li>
        
        <li>
          <%= link_to destroy_user_session_path, method: :delete,class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>Log out
          <% end %>
        </li>
        
        
        <% else %>
        
        <li>
           <%= link_to root_path, class: "nav-link text-light" do %>
             <i class="fas fa-home"></i>Home
           <% end %>
        </li>
           
        <li>
          <%= link_to about_path,class: "nav-link text-light" do %>
           <i class="fas fa-link"></i>About
          <% end %>
        </li> 
        
        <li>
          <%= link_to new_user_registration_path,class: "nav-link text-light" do %>
            <i class="fas fa-user-plus"></i>Sign up
          <% end %>
        </li>
        
        <li>
          <%= link_to new_user_session_path,class: "nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i>Log in
          <% end %>
        </li>
        
        <% end %>
        </ul>
        </div>
        </div>
        </nav>
    </header>
    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
   
    <main>
    <%= yield %>
      
    </main>
    
  </body>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
         <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>   
   </footer>
</html>